version: 2.1

jobs:
  unit-test:
    docker:
      - image: cimg/python:3.9.4
    working_directory: ~/repo
    environment:
      POETRY_VIRTUALENVS_IN_PROJECT: "true"
    steps:
      - checkout
      - run: poetry install
      - run: ls -all

workflows:
  test:
    jobs:
      - unit-test
