version: 2.1

jobs:
  unit-test:
    docker:
      - image: cimg/python:3.9.4
    working_directory: ~/repo
    environment:
      POETRY_VIRTUALENVS_IN_PROJECT: "true"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "poetry.lock" }}
            - v1-dependencies-
      - run: poetry install
      - save_cache:
          paths:
            - ~/.venv
          key: v1-dependencies-{{ checksum "poetry.lock" }}
      - run: make unit-test

workflows:
  test:
    jobs:
      - unit-test
